### ISSUE TITLE
I would love to know your .zshrc

### ISSUE THREAD

**Issue by lyzkov** [Luzifer/cfg#1]
You committed with a symbolic link to hide away .dotfile implementation details. Really? Not a joke. 😈
I feel that some things are waiting to be known and customized in my iHacMag's System Configuration.

**Comment by Luzifer** [comment]
Just follow the link: `~/.zshrc => .zsh/zshrc`

https://github.com/Luzifer/cfg/blob/master/.zsh/zshrc

**Comment by lyzkov** [comment]
😊
